server:
  host: 127.0.0.1
  port: 9090

Redis:
  host: 127.0.0.1
  port: 6379

Mysql:
  host: 127.0.0.1
  port: 3306
  password: root
  dbname: studysystem
  user: root

localfile:
  path: D:/images/

email:
  addr: smtp.qq.com:25
  host: smtp.qq.com
  from: "study_system <xxxxxxx@qq.com>"
  email: xxxxxxxxx@qq.com
  auth: xxxxxxxxxx