server:
  host: 192.168.1.67
  port: 9090

Redis:
  host: 192.168.1.67
  port: 6379
  password: dream

Mysql:
  host: 192.168.1.67
  port: 3306
  password: dream
  dbname: study_system
  user: root

localfile:
  path: D:/images

email:
  addr: smtp.qq.com:25
  host: smtp.qq.com
  from: "study_system <2745969694@qq.com>"
  email: 2745969694@qq.com
  auth: xhteefrzvgasdeig
  expire: 300

pgsql:
  host: 192.168.1.67
  port: 5432
  password: postgres
  dbname: study_system
  user: postgres

Video:
  num:10